# Generated by Django 3.2.6 on 2021-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_post', models.CharField(max_length=50)),
                ('date_post', models.CharField(max_length=10)),
                ('text_post', models.CharField(max_length=300)),
                ('image_post', models.ImageField(upload_to='')),
            ],
        ),
    ]
