# Generated by Django 3.2.6 on 2021-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(max_length=300),
        ),
    ]
